# Generated by Django 6.0.3 on 2026-03-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, verbose_name='Listing Description'),
        ),
    ]
