# Generated by Django 6.0.3 on 2026-03-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('archived', 'Archived')], default='active', max_length=100, verbose_name='Listing Status'),
        ),
    ]
